blueprint:
  name: ESPHome Wizmote to MQTT
  description: Publish WIZmote events to MQTT
  domain: automation
  author: Ken Kauffman DBA Traxeon
  input:
    remote:
      name: Enter mac address for WIZMote (case sensitive)
  
trigger:
  - platform: event
    event_type: esphome.wizmote_action
    event_data:
      mac: !input "remote"
    id: wizmote_action
  - platform: event
    event_type: esphome.wizmote_choose
    event_data:
      mac: !input "remote"
    id: wizmote_choose
condition:
  - condition: trigger
    id:
      - wizmote_action
      - wizmote_choose
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - wizmote_action
        sequence:
          - service: mqtt.publish
            metadata: {}
            data:
              qos: "1"
              topic: wizmote/event/action
              payload_template: "{{ trigger.event.data | tojson }}"
      - conditions:
          - condition: trigger
            id:
              - wizmote_choose
        sequence:
          - service: mqtt.publish
            metadata: {}
            data:
              qos: "1"
              topic: wizmote/event/choose
              payload_template: "{{ trigger.event.data | tojson }}"
mode: restart
