blueprint:
  name: ESPHome Wizmote to MQTT
  description: Publish WIZmote events to MQTT
  domain: automation
  author: Ken Kauffman DBA Traxeon
  input:
    remote:
      name: Enter mac address for WIZMote (case sensitive)
  
trigger:
  - platform: event
    event_type: esphome.wizmote_action
    event_data:
      mac: !input "remote"
    id: wizmote_action
  - platform: event
    event_type: esphome.wizmote_choose
    event_data:
      mac: !input "remote"
    id: wizmote_choose
condition:
  - condition: trigger
    id:
      - wizmote_action
      - wizmote_choose
action:
  - service: mqtt.publish
    data:
      qos: "1"
      payload_template: "{{ trigger.event.data | tojson }}"
      topic: wizmote/event
mode: single
